### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by GiuseppeGalilei** [abdllahdev/nimbus-narratives#2]
Hi, I found your theme on the Astro website. I really like it and I'm considering using it.
However, I noticed that your project is missing a license, can you add it?

**Comment by abdllahdev** [comment]
Thank you for rasing the issue and considering using my theme. I added an MIT license to the project. Feel free to use it as you want 🙂.

**Comment by abdllahdev** [comment]
Closed by #3
